[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scsketch"
version = "0.0.2"
dependencies = [
    "anywidget",
    "jupyter-scatter>=0.21.0",
    "numpy",
    "pandas",
    "scanpy", 
    "matplotlib",
    "requests",
    "umap-learn>=0.5.7",
]
readme = "README.md"

# For projects not using `uv`, you can install these development dependencies with:
# `pip install -e ".[dev]"`
# If you're using `uv` for development, feel free to remove this section.
[project.optional-dependencies]
dev = [
    "watchfiles", 
    "jupyterlab",  
    "llvmlite>=0.44.0", 
    "torch", 
]

# Dependency groups (recognized by `uv`). For more details, visit:
# https://peps.python.org/pep-0735/
[dependency-groups]
dev = [
    "watchfiles", 
    "jupyterlab", 
    "llvmlite>=0.44.0", 
    "torch",
]
